name: Metrics
on:
  # Schedule updates (every day)
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual workflow trigger
  workflow_dispatch:
  # Run on each push to the master branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Tushar-Sukhwal
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B
          plugin_notable: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
      - name: Coding Habits
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
